services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      CASSANDRA_SEEDS: "cassandra"
      CASSANDRA_CLUSTER_NAME: "TestCluster"
      CASSANDRA_START_RPC: "true"
      CASSANDRA_NUM_TOKENS: "256"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"

volumes:
  cassandra-data:
